export const dummyPoojas = [
  {
    id: 1,
    name: 'Satyanarayan Pooja',
    description: 'A sacred Hindu ritual performed to seek blessings for prosperity and well-being.',
    duration: 3,
    price: 2500,
    originalPrice: 3000,
    image: '/images/image15.png',
    category: 'Prosperity',
    rating: 4.9,
    reviews: 1247,
    benefits: ['Prosperity', 'Health', 'Happiness', 'Removal of obstacles'],
    samagri: ['Coconut', 'Banana', 'Flowers', 'Incense', 'Oil lamps', 'Puja materials'],
    priest: 'Pandit Rajesh Sharma',
    experience: '8 years',
    languages: ['Hindi', 'Sanskrit'],
    isPopular: true,
    isOffer: true,
  },
  {
    id: 2,
    name: 'Ganesh Pooja',
    description: 'Worship of Lord Ganesha to remove obstacles and bring success.',
    duration: 2,
    price: 1500,
    originalPrice: 1800,
    image: '/images/image9.jpg',
    category: 'Success',
    rating: 4.8,
    reviews: 2156,
    benefits: ['Success', 'Wisdom', 'Removal of obstacles', 'New beginnings'],
    samagri: ['Modak', 'Flowers', 'Incense', 'Durva grass', 'Puja items'],
    priest: 'Pandit Amit Kumar',
    experience: '6 years',
    languages: ['Hindi', 'English'],
    isPopular: true,
    isOffer: false,
  },
  {
    id: 3,
    name: 'Lakshmi Pooja',
    description: 'Pooja dedicated to Goddess Lakshmi for wealth and abundance.',
    duration: 2,
    price: 2000,
    originalPrice: 2500,
    image: '/images/image17.avif',
    category: 'Wealth',
    rating: 4.9,
    reviews: 1893,
    benefits: ['Wealth', 'Abundance', 'Prosperity', 'Good fortune'],
    samagri: ['Lotus flowers', 'Coins', 'Rice', 'Turmeric', 'Puja materials'],
    priest: 'Pandit Vijay Singh',
    experience: '10 years',
    languages: ['Hindi', 'Sanskrit', 'English'],
    isPopular: true,
    isOffer: true,
  },
  {
    id: 4,
    name: 'Durga Pooja',
    description: 'Celebration of Goddess Durga for strength and protection.',
    duration: 4,
    price: 3500,
    originalPrice: 4000,
    image: '/images/image14.jpg',
    category: 'Protection',
    rating: 5.0,
    reviews: 987,
    benefits: ['Strength', 'Protection', 'Courage', 'Victory over evil'],
    samagri: ['Red flowers', 'Sindoor', 'Weapons', 'Puja items', 'Offerings'],
    priest: 'Pandit Ramesh Gupta',
    experience: '12 years',
    languages: ['Hindi', 'Sanskrit'],
    isPopular: false,
    isOffer: false,
  },
  {
    id: 5,
    name: 'Vishnu Pooja',
    description: 'Worship of Lord Vishnu for peace and harmony.',
    duration: 3,
    price: 2800,
    originalPrice: 3200,
    image: '/images/image16.jpg',
    category: 'Peace',
    rating: 4.7,
    reviews: 1456,
    benefits: ['Peace', 'Harmony', 'Spiritual growth', 'Divine protection'],
    samagri: ['Tulsi leaves', 'Lotus', 'Conch shell', 'Puja materials'],
    priest: 'Pandit Sanjay Mishra',
    experience: '7 years',
    languages: ['Hindi', 'English'],
    isPopular: false,
    isOffer: true,
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'Mrs. Priya Sharma',
    location: 'South Delhi, New Delhi',
    rating: 5,
    text: 'We booked Pandit Ji for our new home Griha Pravesh & Satyanarayan Katha. Pandit Ji arrived 20 minutes early with fresh flowers and all pure samagri. The Vedic chanting was deeply spiritual and our entire family felt blessed.',
    pooja: 'Griha Pravesh & Satyanarayan',
    date: '15 Jan 2026',
    verified: true,
  },
  {
    id: 2,
    name: 'Mr. Rajeshwar Rao',
    location: 'Gurugram, NCR',
    rating: 5,
    text: 'Exceptional service! We needed an urgent same-day Ganesh & Navgrah Shanti pooja. The coordination on WhatsApp was instant, transparent pricing with no hidden dakshina, and the havan was conducted with complete devotion.',
    pooja: 'Ganesh & Navgrah Shanti',
    date: '28 Jan 2026',
    verified: true,
  },
  {
    id: 3,
    name: 'Mrs. Sunita Aggarwal',
    location: 'Noida, Sector 62',
    rating: 5,
    text: 'The Maha Lakshmi & Kuber pooja on Diwali was performed with perfect vidhi and precision. Pandit Ji explained the significance of every mantra. Cleanliness, purity of samagri, and punctuality were top notch.',
    pooja: 'Maha Lakshmi Pooja',
    date: '02 Feb 2026',
    verified: true,
  },
  {
    id: 4,
    name: 'Dr. Amitav Banerjee',
    location: 'Dwarka, New Delhi',
    rating: 5,
    text: 'Organized a Maha Mrityunjaya & Rudra Abhishek for my parents’ health. Pandit Rajesh Ji’s pronunciation of Sanskrit shlokas was flawless. Booking was smooth and hassle-free.',
    pooja: 'Rudra Abhishek & Havan',
    date: '14 Feb 2026',
    verified: true,
  },
  {
    id: 5,
    name: 'Mrs. Meenakshi Iyer',
    location: 'Vasant Kunj, New Delhi',
    rating: 5,
    text: 'Finding authentic Vedic pandits in Delhi used to be difficult. Pujari Baba made it effortless. The samagri kit was complete, right down to dry fruits, pure ghee, and mango wood. Truly divine experience!',
    pooja: 'Vastu Shanti & Havan',
    date: '24 Feb 2026',
    verified: true,
  },
  {
    id: 6,
    name: 'Mr. Vikramjit Singh',
    location: 'Faridabad, NCR',
    rating: 5,
    text: 'Highly professional and spiritually enriching. We booked the Family Blessing package. Both pandit jis were very polite, knowledgeable, and guided us through every ritual with patience.',
    pooja: 'Family Blessing Package',
    date: '05 Mar 2026',
    verified: true,
  },
];

export const packages = [
  {
    id: 1,
    name: 'Family Blessing Package',
    description: 'Complete pooja package for family prosperity and well-being',
    poojas: ['Satyanarayan Pooja', 'Ganesh Pooja'],
    originalPrice: 4000,
    discountedPrice: 3500,
    savings: 500,
    features: ['2 Experienced Priests', 'Complete Samagri', 'Prasad Distribution', 'Family Counseling'],
  },
  {
    id: 2,
    name: 'Wealth & Success Bundle',
    description: 'Combined pooja for wealth attraction and success',
    poojas: ['Lakshmi Pooja', 'Ganesh Pooja'],
    originalPrice: 3500,
    discountedPrice: 3000,
    savings: 500,
    features: ['Premium Priest', 'Gold-plated Items', 'Wealth Yantra', 'Success Mantras'],
  },
  {
    id: 3,
    name: 'Complete Spiritual Package',
    description: 'Comprehensive spiritual cleansing and blessing ceremony',
    poojas: ['Satyanarayan Pooja', 'Vishnu Pooja', 'Durga Pooja'],
    originalPrice: 8800,
    discountedPrice: 7500,
    savings: 1300,
    features: ['Senior Priest', 'Complete Samagri Kit', 'Spiritual Consultation', 'Follow-up Prayers'],
  },
];

export const stats = {
  totalPoojas: 1247,
  happyCustomers: 892,
  experiencedPriests: 15,
  yearsOfService: 1,
};